[green_agent]
agentbeats_id = "019bc5a4-62ec-7710-b513-967eb9397121"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "role_1_name"
env = {}

[[participants]]
agentbeats_id = ""
name = "role_2_name"
env = {}

[config]
num_scenarios = 10
test_level = "all"
# Optional: domains = ["Social Dynamics (Hierarchy/Communication/Face)"]
# Add your assessment config here
