[green_agent]
agentbeats_id = "019bc5a4-62ec-7710-b513-967eb9397121"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[[participants]]
agentbeats_id = "" #kept empty
name = "evaluee"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[config]
num_scenarios = 10
test_level = "all"
# Optional: domains = ["Social Dynamics (Hierarchy/Communication/Face)"]
